import sys, os

SECURE_BOOT_TYPE_DEVELOPMENT = 'Unsigned (XIP) image Boot'
SECURE_BOOT_TYPE_HAB_AUTH    = 'Signed (XIP) Image Boot'
SECURE_BOOT_TYPE_HAB_CRYPTO  = 'HAB Signed Encrypted Image Boot'
SECURE_BOOT_TYPE_BEE_CRYPTO  = 'BEE (Signed) Encrypted XIP Image Boot'

KEY_STORAGE_REGION_OPTMK      = 'Fuse OTPMK'
KEY_STORAGE_REGION_GP4        = 'Fuse GP4'
KEY_STORAGE_REGION_SW_GP2     = 'Fuse SW_GP2 '
KEY_STORAGE_REGION_GP4_SW_GP2 = 'Fuse GP4&SW_GP2'

